name: ML_anime_ratings_analysis

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.11
  - pandas
  - numpy
  - scikit-learn
  - matplotlib
  - scipy
  - joblib
  - threadpoolctl
  - pip

  - pip:
      - hdbscan